pipeline {
    agent any

    environment {
        IMAGE_NAME = "flask-login-app"
        CONTAINER_NAME = "flask-container"
        PORT = "5001"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/omxchavan/jenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME ."
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh "docker run -d -p 8000:$PORT --name $CONTAINER_NAME $IMAGE_NAME"
            }
        }
    }

    post {
        success {
            echo "App deployed successfully on http://localhost:8000"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}